sudo: required
services:
  - docker
language: c
cache: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y realpath # needed on ubuntu 14.04.5 LTS / trusty
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage
  - wget https://raw.githubusercontent.com/mor1/dommage/master/dommage-deploy
  - chmod +x dommage dommage-deploy
  - export PATH=$PATH:$PWD/

script:
  - make configure build
  - dommage-deploy

env:
  matrix:
    - FLAGS="-t unix -vv --kv_ro archive --net socket --port 80"
    - FLAGS="-t unix -vv --kv_ro archive --net direct --port 80"
    - FLAGS="-t xen  -vv --kv_ro archive --net direct --port 80
        --dhcp false --ipv4 46.43.42.134/28 --ipv4-gateway 46.43.42.129"
      DEPLOY=1 XENIMG="decksopenmirageorg"

  global:
  - OCAMLRUNPARAM=b
  - secure: PUu3+Enupf9jcIPD/hs5b6zrNuJagTDXJGtYfSUIFvzevSXZzs6mXPu8L2vvAQbQ8ig/8VLToa44vUTG9OEy9SxXrR6yTQGfj4YxJ5BXKHwhYMTBXnR1e+S1gA4a5tilMa7M/a0hWa1rORv3diMIK3dihjc1m6VzpCK/4vly7KU=
  - secure: crnwZ3MDUA9szI/EuwB9o7plXVF2QCx+JpOazy4SwC2v47Vf5voOEAxh7iFMgGziBqzKGVnDw4/37WHVm5vdgaL4lL2T73F1PqXbiCdhhwZVcf+EAXr8KmoaNXRieL7qPsemQVvPWUiERZRmR2okvm60EqifZA9/dy/48dJIGMI=
  - secure: JijSTl0jOOPL0HoWooCBnhokjqboQSgwy3orgG5nUIPrluthNjix4ujds9TOuEtv2pflbgptUUdYJ7R6VfeZk/UWIVUbwBRjtMJRQRDPB0jxyoL9VLGzTwfdovwV0Rg0jeJkBWsAJjIxkdawE2R4wexAOn/tWDiLaSQh/n096Fc=
  - secure: DUOpC7WiKJHWNcWdlB2T3oQd43p52pGwFOaGX1B9KxYdObnOOScLyMrbVBLl7Y47HHLU1UbgZ1WuilI/ezK2G/pAuq7WLHF9wVw6QyJhiRwhGSFOCKOeScU8LE6Pw4AnKyTDDKL/IY2D94IfcI/db2NI6uzB2rtdVwkqI0f8+4I=
  - secure: dKlWRe8xZmBfg2ZgBiET2KqA+pvrKZHwvqnpm304Fojpyw2C+lEDUo6DQOLEThDeih28FOU3rlUCtxasJQpDWw52CRseXYVqaX2UuNzvmv8TqrVXTxv/gZgpM50xCKCRCDEEgznH7hby1z34MxrUAEMDd4LkQXKjr8sv2aH0FNA=
  - secure: TFOc5f/EA7WROfKW/tZZJbRr+HVjojRvmjGvXTO1BPec0/bBS0khAD8ozd1v938lIN0f81P26ZMcQlvsBB+EFfo7yZyYztmBAAPSaKaMu87aYi/pzEr7oNL8I8UlV0Rri1SHAEOKKoF9s9M4dYDxhXNbIuoCpnN89sXld2nk4fE=
  - secure: BJJDKHqZfZWTk3Wf0osT1NOHb50BLMjA+iSaftwH2HsBhtGT2BpvqFq34p2HE2mv/+2QB2a/A4ajj1ePMw03SqD83X4DjYCUh73Pc1PYbqEJ1kL6ivaGC7gxVbT/2WtPxXPGnCZ0sooMY/CQWrlx5PMWZZtxHQootkZ6XpKOsWM=
  - secure: cZpbGeWcGCicdY1pyBuGaioaK9eh/KixqrKcaaqH8I3IWbLthDdwSNVNjcXO67kIb6jXA6/6TX7E5xxTQe80LbIuarNSLJvtqnh1A9yppVA3SYQI7sY8hjk8uolm+qnAtEZKxlUl/T5zxFmokP6MKp7wDUZJPSk3JiN0xwuzhuc=
  - secure: aZ71DJ4wXOZcdVoMSJvWg2hSMJrTczbb/ZNZISrj3dcgLojnsX1s/1tlVovNetDzKLlW4gdQIO/PgOL5z6dZRS/IJvZvPrUKWtkt6R2xKnnQU+fgeziIfltN7rXMT4GFcSaJHl6S53XnnnCMqkc2jjhmxEt36xwVr1yU7onM6gE=
  - secure: EuanehUlVIL/qJLD0j4CfbqDW0MIKbIVu2aRwwbbNK2LgQtr/kDJSVrtwEEFddOxC2ZmbGxmUC4TCZ6yFlpfQkr6UnyYmnINb/EL2ocvay6/PAFXcDRtCNWd7MzfiUfTIPxg7qwYBqabgdJ/iKlRrFgHOeSts3OhBZs4MzD62GY=
  - secure: Juipi/OO05oERAttsFLSow5M1P8YPb3vigGgufaedSI5KjzcPrU6PeKtX6D7nHCbzjZEIj3uRnv9VC8eT46JC7IYQs4ATGnEQnJsGoE2gHWQ348UlK7o/jgPtG9XeYaTgxN4N/hOKk/B08MIJwsJllUUZvBztUIJlUddrFOt0xE=
  - secure: Qq8YWXsJk3R0EJIMnT7cScCp8xDAG5z3Q2seA8d8P2LaR/1FvHkZGUMXwJ27f1ZvOmtBCEhcXbYtYFfedXJwy4JGRWq165te20XZS0gqpdi5DHbv0S1rlE01bdcQFVQSvxeMXsO+KdUmrx9+yjG1r4CarB+m5CpHHJdIs9mxb/c=
  - secure: dIRmXAwM8EVjni3k0POewi0eMXB7Ebr/sTJhYPUYA31TrW98OYO6P2VCR4zND5e7ObmM1pyjXlsP/i6Q8YTch3xxJgBeYOCbsb7BfJ62UioGdWL2E5wlrnDPgHxdPayDajRgmxRjY6EErAfaFv+Kk2OmeeIv4ibfMoMzSGjQT+A=
  - secure: NitRQnkoKrvEdEM0ok4LLRb3wboSFtdrMqyg07sOFr6g08Z27eJ5e+mVw+f9Wzd3JHlgfaD0aAtLa84UsQ9r7iXOCnwhb1FnKGW5b3zBcFYkvKb7fds3eAay/ovhkJgU9O0EIu1pbOoEP7GeywS2uvW43ulxdBS9BMfDL/t1FsE=
  - secure: IexlwG0ABmi+T848NBETv6dbzWxj40b3aLGXZGTPdHAQ7NJmhE4h1P8KwbLDzUj09n+kim2JCMp5j2JOWODV7DyCJ+grcaxQAsqoADfdmGsdohJ4hNhj1VrcUHNxmWilzj8aF/JUA8OdaH1a1WYEySQfVf3EYiE57fX8qR27yUY=
  - secure: M97P/EApVsJsnlQwXphuBkMYudPOXUG9Q/0LZikTJtZzVOH4zSWQ9eOLiVkDQ1+EpIMCrEPO6FZl1twlVQqZ4o/1jfZWKOPGbYRJacqojN2LLKdA9Rr6BwCxW7IVm+ui9zJAxxZWf1o3vkJgfwdwsdehrhDpBlNRIuu96L8t7DY=
  - secure: I/YzDU7BMIXbbUu6p3d0NZM22FR3skU7IaLhamWjKhcjAvs/+iNt9/NABDh+c7uIo3ep2N4fwe9aJj36RS4icJpgEhtbJL3fU+nDa8oW7xXDD7xY3EHfmAL5h8fi2faytO62eXPbCBovqwDCh2Ky3Xz0npfdnoNWLc3+KqmOmkg=
  - secure: qTYhrR49lUf0Xw2kcmsBvt2m2PxHR8oXlwlAIfvnOmCiGyuGvAsLhQYmx57FlUwYwoCqU/QaKKNSBlKmsw6cM//qjPD33QBh1W/m3oka59G2oopPW2IupdA2PxO9f7296LWsL2+SbIxVqhOjNDG022+WXkB0q+HXrvMdoyqfWrg=
  - secure: TQyRio8OpN1mDIpbknhHcq9MlWD3/f2KTmTkEQurnIoEC5YVUgTqVGabTFy36Oyn7Kkl4phe7QXOWS9N90lQ9InjZNqnWLwZzWmcaCOnIY70QAtxlUzEQg26D/vTWtbB8GXEKiuV2JXA48S2Zm2YxQqPuVD2lB+B4M7Kll05FRM=
  - secure: m9y7l1RKyllUrYfgKsu4tLI8Jxh49ooQ7/kk35WBMG9TVT0II6hWJ+FhdYiV9p/oZx/Bd9TCSO2FNuHV0+X3nUyqMsmR2wU/Ne3bnC6N99YrHnfmTMotO1iBZeTBAJGZCSPl0acR3OnMYX2j1Nw5gYrpHpd7W4AthEuRNJPEo5w=
  - secure: avZHFg3evccKBaHbbOIHrch+FyfiWiPWSS2vxmFU7SNcRqXTxyEXmRm4F60CZJo1hxaonO7/grbNpPFKIEx5zPKqSpDPXcJt5485hokA41aDaYwXuewJBqaWSjLBpWxd3Wq4wXXHP5Bc+eXlXor2c6q9RejsS4osRCRgof87L8o=
  - secure: ek5DLphp+/t24bCrE3WEOa2KqobaG/Fr71EJy5+EuY5WrjAR8BJeDyezVWnWzfjKc0cdo/l5yVNE66PDq9p2m9xXys6Po+Ub1H2fUvLcenEP6BlyHhhzdNa5KmWUYTJQ71BOrkcr1s7QmWbVdnca0uzZ8asMSW9EzZuO5cLXP7o=
  - secure: ZMlTRxsWk8ppWul22ErmpgWNgJgKFW55wclG4r9DIoWtuy9E1pPmp5JIwFFFNfZTswkJAcGcQzr/ts+t/WygTFeZxNp1wD2T6GGzzptpk9B2Zr63+dSM8FHGXNm1FAqtKAskXj0mB2V3NZcfi6TZbuCx8PQ5bRNuhexAgZgjMpM=
  - secure: qLgVtNzvicJFnowYXV0kcQOKvQuKh8YDD6nWxhF1fB/kGN8NgJ5kJqT2uhEuLA3ptyshLdSvyQZO/kgZrgIw+XweRqmidLyd7sWkhm58F/AIpMSyX7vrCCaQwROgdmyPMUESL9MWnUqbEv1amYTmmqP+Kw+fd5GU5KnLMg/bDOg=
  - secure: nx13Qqon3sg4a/zZBoL0cSZ81JK30JmpGQf4EEHwsvLQpWPaPWInLyRn3V38yQmC8P21y8byy66AVnQFMvl8qZW8Tyuhqanu4QQzgbKPck5kgMEr9BkNXNQl51UR4HLIcNCraAICZ1mBO3hshDEOm1Sl2Rr2h84mqtEXyggnEs4=
  - secure: F8F/wx9SXJHidHvfmalRcdKR+pcvrbMe1WVjNQDudU2RGcO/iknVpO77wMsM470o8iH7DruBIy/3FWCm8p9Z33LSzmbrSZeCzgGYJWx02Siy7BFrPr9jcftiB9vU7eRMuvBdoTS9rxpeHZ3hhajV4CgC0VtDyOB9ZjiQZLBgha8=
